Reduce generated binary size
aws/aws-lambda-builders pull request #210
Opened 2020-11-12 03:53 UTC by cgarvis

Adding the `ldflags` `-s -w` will reduce the size of the generated binary.

-s  disable symbol table
-w  disable DWARF generation

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-16 19:46 UTC, CoshUS requested changes

2021-03-16 19:46 UTC, CoshUS commented on aws_lambda_builders/workflows/go_modules/builder.py
> +            cmd += ["-ldflags='-s -w'"]
@cgarvis 
Thanks for the PR! 
Can you also update the related unit test `tests/unit/workflows/go_modules/test_builder.py::TestGoBuilder::test_run_executes_bundler_on_nixes`?

2021-03-16 20:07 UTC, hoffa commented
Doesn't this strip symbols from stack traces, making debugging much harder?

Also there's precedent to stripping Go binaries causing issues: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717172

I'd vote against such a broad-brush approach unless the Go team explicitly recommends this as a supported approach.

2021-11-23 22:12 UTC, jfuss commented
Given https://github.com/aws/aws-lambda-builders/pull/210#issuecomment-800567284, I am going to close this as won't fix. If this is still something we should do, please open an issue so we can discuss this further.

2021-11-23 22:12 UTC, closed without merging