chore: Update branch, repo for build/test action
aws/aws-lambda-builders pull request #412
Opened 2022-12-05 23:02 UTC by mildaniel

*Description of changes:*
Have the new GitHub actions only run against the `develop` branch and only against this repository.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-06 17:08 UTC, jfuss requested changes

2022-12-06 18:59 UTC, mildaniel commented on .github/workflows/build.yml
> +      - develop
We shouldn't be raising PRs to `main` anymore with the new automated releases.

2022-12-07 19:43 UTC, jfuss approved these changes

2022-12-07 19:43 UTC, jfuss commented on .github/workflows/build.yml
> +      - develop
That makes sense. Thanks for clarifying.

2022-12-08 19:22 UTC, lucashuy approved these changes

2022-12-08 19:22 UTC, merged